package:
  name: fortress
  version: 0.1.0

source:
  path: ..

build:
  binary_relocation: true

requirements:
  build:
    - flap
    - fruit 
    - fruitpy
    - fypp
    - json-fortran
    - numpy 

  run:
    - flap
    - fruit
    - fruitpy
    - lapack
    #- mpich2
    - tqdm

test:
  files:
    - ../test

  source_files:
    - test
    - makefile
    
  requires:
    - fruitpy
    - fortress
    - lapack
    #- mpich2
    - json-fortran
    - openblas


    
