package:
  name: fortress
  version: '0.1.3'

source:
  path: ..

build:
  binary_relocation: True
  detect_binary_files_with_prefix: True
    
requirements:
  build:
    - python
    - flap
    - fruit 
    - fruitpy
    - fypp
    - json-fortran
    - numpy 

  run:
    - python
    - flap
    - fruit
    - fruitpy
    - openblas
    - mpich2
    - tqdm
    - json-fortran 
    - numpy
    - tqdm
    - pandas
test:
  imports:
    - fortress

test:
  source_files:
    - test
    - makefile
    - src

#   requires:
#     - fruitpy
#     - fortress
#     - lapack
#     #- mpich2
#     - json-fortran
#     - openblas


    
