package:
  name: fortress
  version: 0.1.0

source:
  path: ..

build:
  binary_relocation: true

  features:
    - ifort

script_env:
  - LD_LIBRARY_PATH #[linux]
    
requirements:
  build:
    - ifort
    - flap
    - fruit 
    - fruitpy
    - fypp
    - json-fortran
    - mpich2
    - intelpython3_core
  run:
    - ifort
    - flap
    - fruit
    - fruitpy
    - mpich2
    - intelpython3_core
test:
  files:
    - ../test
    - ../makefile
    - ../test_driver.f90
  source_files:
    - test
    - makefile
    - test_driver.f90
  requires:
    - fruitpy
    - fortress
    - mpich2
    - json-fortran
